"""Initial migration

Revision ID: cb19dfab93c2
Revises: 
Create Date: 2025-02-02 02:16:40.008176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb19dfab93c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confession',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('hobbies', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('previous_relationships', sa.Integer(), nullable=True),
    sa.Column('previous_dates', sa.Integer(), nullable=True),
    sa.Column('insta_id', sa.String(length=100), nullable=True),
    sa.Column('ideal_weekend', sa.String(length=50), nullable=True),
    sa.Column('music_taste', sa.String(length=100), nullable=True),
    sa.Column('societies', sa.String(length=500), nullable=True),
    sa.Column('favorite_sports', sa.String(length=200), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('leisure_activities', sa.String(length=100), nullable=True),
    sa.Column('personality_type', sa.String(length=50), nullable=True),
    sa.Column('sleep_schedule', sa.String(length=50), nullable=True),
    sa.Column('aspirations', sa.String(length=50), nullable=True),
    sa.Column('dream_date', sa.String(length=255), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('relationship_looking_for', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('confession_like',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('confession_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confession_id'], ['confession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'confession_id', name='unique_user_confession_like')
    )
    op.create_table('date_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('parent_request_id', sa.String(length=36), nullable=True),
    sa.Column('is_blind_date', sa.Boolean(), nullable=True),
    sa.Column('last_altered_by', sa.String(length=36), nullable=True),
    sa.Column('last_action_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_altered_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_request_id'], ['date_request.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_request')
    op.drop_table('confession_like')
    op.drop_table('user')
    op.drop_table('otp')
    op.drop_table('confession')
    # ### end Alembic commands ###
